export const waterTypeOptions = {
  'Rivers and Streams': [
    'BLACKWATER SYSTEM',
    'DITCH OR CANAL',
    'CREEK',
    'STREAM, EPHEMERAL',
    'CONNECTING CHANNEL',
    'WASH',
    'STREAM, TIDAL',
    'GULCH',
    'RIVER, TIDAL',
    'RIVER, WILD RICE',
    'DRAIN',
    'RIVER',
    'CHANNEL',
    'CREEK, INTERMITTENT',
    'STREAM/CREEK/RIVER',
    'STREAM',
    'SPRING',
    'STREAM, COASTAL',
    'STREAM, INTERMITTENT',
    'STREAM, PERENNIAL',
  ],
  Other: ['RIVERINE BACKWATER', 'FLOWAGE', 'BAYOU'],
  'Lakes and Reservoirs Shoreline': ['INLAND LAKE SHORELINE'],
  'Lakes and Reservoirs': [
    'RESERVOIR EMBAYMENT',
    'RESERVOIR',
    'LAKE, WILD RICE',
    'POND',
    'LAKE, FRESHWATER',
    'LAKE, SPRINGS',
    'IMPOUNDMENT',
    'LAKE',
    'CIRQUE LAKE',
    'LAKE, PLAYA',
    'LAKE/RESERVOIR/POND',
    'LAKE, SALINE',
    'LAKE, NATURAL',
  ],
  'Coastal Waters': [
    'BAY/ESTUARY',
    'BAY',
    'ESTUARY',
    'OCEAN',
    'HARBOR',
    'OCEAN/NEAR COASTAL',
    'ESTUARY, FRESHWATER',
    'GULF',
    'SOUND',
    'LAGOON',
    'INLET',
  ],
  'Coastal Waters Shoreline': [
    'BEACH',
    'COASTAL & BAY SHORELINE',
    'COASTAL',
    'ISLAND COASTAL WATERS',
  ],
  Wetlands: [
    'WETLANDS, TIDAL',
    'WETLANDS, DEPRESSIONAL',
    'WETLANDS, SLOPE',
    'WETLANDS, RIVERINE',
    'MARSH',
    'WETLANDS, FRESHWATER',
    'WETLAND',
  ],
  'Great Lakes Shoreline': [
    'GREAT LAKES BEACH',
    'GREAT LAKES SHORELINE',
    'GREAT LAKES CONNECTING CHANNEL',
  ],
  'Great Lakes': ['GREAT LAKES OPEN WATER', 'GREAT LAKES BAYS AND HARBORS'],
  Watershed: ['WATERSHED'],
  'Sink Hole': ['SINK HOLE'],
};
