export default {
  items: [
    {
      ss_seq: 1617,
      rgn_code: '06',
      state: 'LA',
      ss_title:
        'Implementing Agricultural Best Management Practices Reduces Total',
      ss_overview:
        'As far back as 2002, the Louisiana Department of Environmental Quality (LDEQ) Integrated Report (IR) has indicated total dissolved solids (TDS), total suspended solids (TSS), sedimentation/siltation and turbidity as impairments to fish and wildlife propagation (FWP) use support in Bayou Queue de Tortue. LDEQ chose Bayou\nQueue de Tortue, LDEQ subsegment 050501, as one of the 40 priority watersheds and partnered with the Louisiana Department of Agriculture and Forestry (LDAF) and the U.S. Department of Agriculture (USDA) Natural Resources Conservation Service (NRCS) to implement best management practices (BMPs) to improve the health of the waterbody. The 2014 IR shows that FWP is no longer impaired due to TDS. It remains impaired by turbidity, but water quality data show progress. As far back as 2002, the Louisiana Department of Environmental Quality (LDEQ) Integrated Report (IR) has indicated total dissolved solids (TDS), total suspended solids (TSS), sedimentation/siltation and turbidity as impairments to fish and wildlife propagation (FWP) use support in Bayou Queue de Tortue. LDEQ chose Bayou\nQueue de Tortue, LDEQ subsegment 050501, as one of the 40 priority watersheds and partnered with the Louisiana Department of Agriculture and Forestry (LDAF) and the U.S. Department of Agriculture (USDA) Natural Resources Conservation Service (NRCS) to implement best management practices (BMPs) to improve the health of the waterbody. The 2014 IR shows that FWP is no longer impaired due to TDS. It remains impaired by turbidity, but water quality data show progress. As far back as 2002, the Louisiana Department of Environmental Quality (LDEQ) Integrated Report (IR) has indicated total dissolved solids (TDS), total suspended solids (TSS), sedimentation/siltation and turbidity as impairments to fish and wildlife propagation (FWP) use support in Bayou Queue de Tortue. LDEQ chose Bayou\nQueue de Tortue, LDEQ subsegment 050501, as one of the 40 priority watersheds and partnered with the Louisiana Department of Agriculture and Forestry (LDAF) and the U.S. Department of Agriculture (USDA) Natural Resources Conservation Service (NRCS) to implement best management practices (BMPs) to improve the health of the waterbody. The 2014 IR shows that FWP is no longer impaired due to TDS. It remains impaired by turbidity, but water quality data show progress. ',
      ss_type: '1',
      num_wb_restored: null,
      type1_fiscal_year: 2016,
      publication_date: '2018-02-14T05:00:00Z',
      web_link:
        'https://www.epa.gov/sites/production/files/2018-02/documents/la_bayouqueuedetortue_1617_508.pdf',
      grts_prj_ids: null,
      notes:
        '1. Abstract - "to improve the health of the water body." Did you partner with LDAF and NRCS to reduce loadings affecting TDS and turbidity, and thus restore the FWP standard? The abstract is not clear in how the LDAF BMPs would have an effect on the TDS and turbidity loadings as it states, "Dredging has caused a reduction in flow velocity and eroding spoil banks have increased the amount of solids." Yet, in the problem paragraph, it list suspected sources as irrigated crop production, atmospheric deposition - toxics. Then it says flow alterations from water Diversions and non-irrigated crop production. This is confusing.\n2. The problem statement will need to coincide with the abstract.\n3. You need photos are the eroding banks, and how it looks now - which hopefully will indicate the difference that the BMPs made in reducing solids to the bayou.\n4.You may want to better link the grade structures with having an effect on reducing TDS. show a picture.\n5. The 2014 IR would be produced from WQ data collected in 2013, and earlier. How could the BMPs that were implemented beginning in April and October, 2013, have had any effect on the load reduction numbers associated with the WQ data that went into the 2014 IR?\n6. Project Highlights - probably should summarize the BMPs - record keeping, for instance, may not be the most convincing unit to help with reducing loads. Also, the shallow water for wildlife should not have been considered a benefit to reducing TDS loadings, as well as pest mgmt. Hopefully, 319 was not used for these.\n7. "Results" - The waterbody remains impaired for DO and turbidity, and the expectation that turbidity will be addressed in 2016. What are the expectations that DO will be addressed with the same BMPs?\n8. Under the Watershed Plan section, place reference in the notes to state when the plan was approved by EPA.\n\nPlease revisit this SS - and clear this up. Headquarters would send this back. Thanks.\n\nAdam Jorge:Change poll listings.10.23.17',
      plncat_types: null,
      prj_hlight_bmp_comments:
        'LDAF began implementing BMPs in 2004 and completed implementation in January 2017. BMPs implemented to date include conservation crop rotation (328 sites; 1,117.4 acres [ac]), residue management (344 sites; 6,008.2 ac), grade stabilization structures (410 sites; 32 ac), irrigation land leveling (464 sites; 4,638.72 ac), shallow water for wildlife (646 sites; 3,112.4 ac), nutrient management (590 sites; 17,052.2 ac), pest management (595 sites; 17,052.2 ac), record keeping (tracking pesticide and nutrient use to avoid overapplication) (748 sites; 17,052.2 ac), and dry seeding (2,232.4 ac).\n\nA watershed implementation plan was developed for Bayou Queue de Tortue in 2013. Bayou Queue de Tortue was made a priority in The Gulf of Mexico Initiative (GoMI). BMP implementation occurred in 2012–2014 to improve ecosystem health in the Gulf of Mexico, and also as part of the National Water Quality Initiative (NWQI) starting in 2014. \n\nAfter reviewing the BMPs implemented and their purposes, LDEQ determined that the most effective in reducing the TDS loads are the grade stabilization structures (constructed between October 2013 and September 2016) and the irrigation land leveling technique (implemented between April 2013 and March 2017) (Figure 2).\n\nLDEQ and its partners began to see steady improvement in the TDS levels in early 2016. LDEQ plans to continue monitoring improvements from BMP implementation, and will use the information to apply to future restoration efforts in other watersheds. ',
      submit_by: null,
      report: null,
      problem_comments:
        'Bayou Queue de Tortue is 56 miles long and flows from the city of Duson to the Mermentau River in Riceville, Louisiana (Figure 1). The bayou receives much of its flow from agricultural runoff from rice and soybean production, and is heavily hydromodified in the upper and middle reaches. Dredging has caused a reduction in flow velocity and eroding spoil banks have increased the amount of solids found in the water column contributing to high turbidity and TDS.\n\nLDEQ has listed the FWP use in this subsegment as impaired since 2002 with suspected causes of impairments including low dissolved oxygen (DO), turbidity, TSS, TDS, sedimentation/siltation, phosphorus (total), nitrate/nitrite (nitrate + nitrite as N), mercury in fish tissue and Fipronil (a broad-spectrum insecticide).\nSuspected sources of impairments were irrigated crop production, atmospheric deposition–toxics, natural conditions, flow alterations from water diversions, and non-irrigated crop production. ',
      partner_fund_comments:
        'DEQ spent a total of $108,350 of Clean Water Act (CWA) section 319 funds on the Bayou Queue de Tortue Project: $10,350 on laboratory analysis and $98,000 on sampling staff and supplies. LDAF and NRCS were instrumental in implementing BMPs in the Bayou Queue de Tortue watershed. A total of 5,827.8 acres are currently under contract. The total payments made in the Bayou Queue de Tortue CWA section 319 project from LDAF are $981,777.67 from 2013 to 2017. The total match received is $1,337,336.58. The conservation programs used to support the goals and objectives of the GoMI are the USDA’s Environmental Quality Incentives Program (EQIP), Conservation Stewardship Program, Wetlands Reserve Program, Grasslands Reserve Program, and the Farm\nand Ranch Lands Protection Program. This watershed project receives EQIP funds which in some cases are leveraged by funds from local and state partners. The sign up for the Bayou Queue de Tortue 319 Project\noccurred in February 2013. The Acadia and Vermilion Soil and Water Conservation District boards set a cap\nof $40,000 per contract with a maximum of one contract per farm entity per parish. A total of 45 applications\nwere received and 38 contracts were written for a total of $1,059,967. The total amount allocated for\nBMPs was $1,075,000. ',
      results_comments:
        'As a result of BMP implementation, water quality has improved, prompting LDEQ to remove TDS as a cause of FWP impairment in the 2014 IR. The FWP use is considered impaired if more than 30 percent of the TDS samples for a reporting period (typically one year) exceed 260 milligrams per liter (mg/L). The ambient water quality network data in Figure 3 shows only one TDS exceedance between May 2012 and September 2016, well below the 30 percent threshold.\n\nIn 2014 the TSS sedimentation/siltation and turbidity impairment classifications were combined and listed simply as turbidity. Although turbidity is still indicated as a cause of impairment to FWP, the ambient and monitoring data show a downward trend throughout 2016. Only two data points exceed 150 nephelometric turbidity units (NTU), a criterion for FWP use support in the Mermentau River (downstream of Bayou Queue de Tortue). In the watershed implementation plan, LDEQ predicted that the average turbidity would be reduced to 149 NTU by 2016. The average of the 2016 monitoring data is 84 NTU, which is 44 percent better than predicted!',
      is_tribal: null,
      tribe_id: null,
      cultural_connection: null,
      is_public: null,
      wb_ids:
        'BAYOU QUEUE DE TORTUE-FROM HEADWATERS TO MERMENTAU RIVER [LA050501_00]',
      pollutants: 'Agriculture',
    },
    {
      ss_seq: 1618,
      rgn_code: '06',
      state: 'LA',
      ss_title:
        'Federal & State Partnerships Remediate Legacy Mine and Improve Water Quality in Harshaw Creek',
      ss_overview:
        'Historical mining activities in southern Arizona’s Harshaw Creek basin left a legacy of mining waste that produced acid mine drainage. The Arizona Department of Environmental Quality (ADEQ) added a three-mile stretch of Upper Harshaw Creek (HUC 15050301-025A) to its 1996 and 1998 Clean Water Act (CWA) section 303(d) lists for impairments due to copper and acidity. ADEQ completed a total maximum daily load (TMDL) for copper and acidity in 2003. The U.S. Forest Service (USFS) conducted land reclamation and remediation work in the Harshaw Creek area between 2016 and 2019. This work helped to control acid mine drainage in the basin, which resulted in a measurable water quality improvement.',
      ss_type: '1',
      num_wb_restored: null,
      type1_fiscal_year: 2022,
      publication_date: '2018-02-14T05:00:00Z',
      web_link:
        'https://www.epa.gov/system/files/documents/2022-10/AZ_Harshaw%20Creek_2019_508.pdf',
      grts_prj_ids: null,
      notes:
        '1. Abstract - "to improve the health of the water body." Did you partner with LDAF and NRCS to reduce loadings affecting TDS and turbidity, and thus restore the FWP standard? The abstract is not clear in how the LDAF BMPs would have an effect on the TDS and turbidity loadings as it states, "Dredging has caused a reduction in flow velocity and eroding spoil banks have increased the amount of solids." Yet, in the problem paragraph, it list suspected sources as irrigated crop production, atmospheric deposition - toxics. Then it says flow alterations from water Diversions and non-irrigated crop production. This is confusing.\n2. The problem statement will need to coincide with the abstract.\n3. You need photos are the eroding banks, and how it looks now - which hopefully will indicate the difference that the BMPs made in reducing solids to the bayou.\n4.You may want to better link the grade structures with having an effect on reducing TDS. show a picture.\n5. The 2014 IR would be produced from WQ data collected in 2013, and earlier. How could the BMPs that were implemented beginning in April and October, 2013, have had any effect on the load reduction numbers associated with the WQ data that went into the 2014 IR?\n6. Project Highlights - probably should summarize the BMPs - record keeping, for instance, may not be the most convincing unit to help with reducing loads. Also, the shallow water for wildlife should not have been considered a benefit to reducing TDS loadings, as well as pest mgmt. Hopefully, 319 was not used for these.\n7. "Results" - The waterbody remains impaired for DO and turbidity, and the expectation that turbidity will be addressed in 2016. What are the expectations that DO will be addressed with the same BMPs?\n8. Under the Watershed Plan section, place reference in the notes to state when the plan was approved by EPA.\n\nPlease revisit this SS - and clear this up. Headquarters would send this back. Thanks.\n\nAdam Jorge:Change poll listings.10.23.17',
      poll_sources: 'Other',
      prj_hlight_bmp_comments:
        'LDAF began implementing BMPs in 2004 and completed implementation in January 2017. BMPs implemented to date include conservation crop rotation (328 sites; 1,117.4 acres [ac]), residue management (344 sites; 6,008.2 ac), grade stabilization structures (410 sites; 32 ac), irrigation land leveling (464 sites; 4,638.72 ac), shallow water for wildlife (646 sites; 3,112.4 ac), nutrient management (590 sites; 17,052.2 ac), pest management (595 sites; 17,052.2 ac), record keeping (tracking pesticide and nutrient use to avoid overapplication) (748 sites; 17,052.2 ac), and dry seeding (2,232.4 ac).\n\nA watershed implementation plan was developed for Bayou Queue de Tortue in 2013. Bayou Queue de Tortue was made a priority in The Gulf of Mexico Initiative (GoMI). BMP implementation occurred in 2012–2014 to improve ecosystem health in the Gulf of Mexico, and also as part of the National Water Quality Initiative (NWQI) starting in 2014. \n\nAfter reviewing the BMPs implemented and their purposes, LDEQ determined that the most effective in reducing the TDS loads are the grade stabilization structures (constructed between October 2013 and September 2016) and the irrigation land leveling technique (implemented between April 2013 and March 2017) (Figure 2).\n\nLDEQ and its partners began to see steady improvement in the TDS levels in early 2016. LDEQ plans to continue monitoring improvements from BMP implementation, and will use the information to apply to future restoration efforts in other watersheds. ',
      submit_by: null,
      report: null,
      problem_comments:
        'Bayou Queue de Tortue is 56 miles long and flows from the city of Duson to the Mermentau River in Riceville, Louisiana (Figure 1). The bayou receives much of its flow from agricultural runoff from rice and soybean production, and is heavily hydromodified in the upper and middle reaches. Dredging has caused a reduction in flow velocity and eroding spoil banks have increased the amount of solids found in the water column contributing to high turbidity and TDS.\n\nLDEQ has listed the FWP use in this subsegment as impaired since 2002 with suspected causes of impairments including low dissolved oxygen (DO), turbidity, TSS, TDS, sedimentation/siltation, phosphorus (total), nitrate/nitrite (nitrate + nitrite as N), mercury in fish tissue and Fipronil (a broad-spectrum insecticide).\nSuspected sources of impairments were irrigated crop production, atmospheric deposition–toxics, natural conditions, flow alterations from water diversions, and non-irrigated crop production. ',
      partner_fund_comments:
        'DEQ spent a total of $108,350 of Clean Water Act (CWA) section 319 funds on the Bayou Queue de Tortue Project: $10,350 on laboratory analysis and $98,000 on sampling staff and supplies. LDAF and NRCS were instrumental in implementing BMPs in the Bayou Queue de Tortue watershed. A total of 5,827.8 acres are currently under contract. The total payments made in the Bayou Queue de Tortue CWA section 319 project from LDAF are $981,777.67 from 2013 to 2017. The total match received is $1,337,336.58. The conservation programs used to support the goals and objectives of the GoMI are the USDA’s Environmental Quality Incentives Program (EQIP), Conservation Stewardship Program, Wetlands Reserve Program, Grasslands Reserve Program, and the Farm\nand Ranch Lands Protection Program. This watershed project receives EQIP funds which in some cases are leveraged by funds from local and state partners. The sign up for the Bayou Queue de Tortue 319 Project\noccurred in February 2013. The Acadia and Vermilion Soil and Water Conservation District boards set a cap\nof $40,000 per contract with a maximum of one contract per farm entity per parish. A total of 45 applications\nwere received and 38 contracts were written for a total of $1,059,967. The total amount allocated for\nBMPs was $1,075,000. ',
      results_comments:
        'As a result of BMP implementation, water quality has improved, prompting LDEQ to remove TDS as a cause of FWP impairment in the 2014 IR. The FWP use is considered impaired if more than 30 percent of the TDS samples for a reporting period (typically one year) exceed 260 milligrams per liter (mg/L). The ambient water quality network data in Figure 3 shows only one TDS exceedance between May 2012 and September 2016, well below the 30 percent threshold.\n\nIn 2014 the TSS sedimentation/siltation and turbidity impairment classifications were combined and listed simply as turbidity. Although turbidity is still indicated as a cause of impairment to FWP, the ambient and monitoring data show a downward trend throughout 2016. Only two data points exceed 150 nephelometric turbidity units (NTU), a criterion for FWP use support in the Mermentau River (downstream of Bayou Queue de Tortue). In the watershed implementation plan, LDEQ predicted that the average turbidity would be reduced to 149 NTU by 2016. The average of the 2016 monitoring data is 84 NTU, which is 44 percent better than predicted!',
      is_tribal: null,
      tribe_id: null,
      cultural_connection: null,
      is_public: null,
      wb_ids:
        'BAYOU QUEUE DE TORTUE-FROM HEADWATERS TO MERMENTAU RIVER [LA050501_00]',
      pollutants: 'Other',
    },
    {
      ss_seq: 1619,
      rgn_code: '06',
      state: 'LA',
      ss_title:
        'Erosion Control and Natural Degradation of Pesticides Leads to a Decline in Pollutants in the Middle Gila River',
      ss_overview:
        'Historical pesticide use in the Middle Gila River watershed contaminated aquatic life, making it unsafe for consumption. Based on these conditions, 12 segments within the Middle Gila River watershed were added to Arizona’s 2002 Clean Water Act (CWA) section 303(d) list for pesticide impairments (i.e., dichlorodiphenyltrichloroethane [DDT], chlordane and toxaphene). The natural degradation of the chemical constituents within the ecosystem, combined with landowner implementation of best management practices (BMPs), decreased pesticide levels in the watershed over time. Based on this improvement, Arizona removed 12 segments within the Middle Gila River watershed from itsimpaired waters list in 2014.',
      ss_type: '1',
      num_wb_restored: null,
      type1_fiscal_year: 2018,
      publication_date: '2018-02-14T05:00:00Z',
      web_link:
        'https://www.epa.gov/sites/production/files/2016-11/documents/az_middle_gila_508.pdf',
      grts_prj_ids: null,
      notes:
        '1. Abstract - "to improve the health of the water body." Did you partner with LDAF and NRCS to reduce loadings affecting TDS and turbidity, and thus restore the FWP standard? The abstract is not clear in how the LDAF BMPs would have an effect on the TDS and turbidity loadings as it states, "Dredging has caused a reduction in flow velocity and eroding spoil banks have increased the amount of solids." Yet, in the problem paragraph, it list suspected sources as irrigated crop production, atmospheric deposition - toxics. Then it says flow alterations from water Diversions and non-irrigated crop production. This is confusing.\n2. The problem statement will need to coincide with the abstract.\n3. You need photos are the eroding banks, and how it looks now - which hopefully will indicate the difference that the BMPs made in reducing solids to the bayou.\n4.You may want to better link the grade structures with having an effect on reducing TDS. show a picture.\n5. The 2014 IR would be produced from WQ data collected in 2013, and earlier. How could the BMPs that were implemented beginning in April and October, 2013, have had any effect on the load reduction numbers associated with the WQ data that went into the 2014 IR?\n6. Project Highlights - probably should summarize the BMPs - record keeping, for instance, may not be the most convincing unit to help with reducing loads. Also, the shallow water for wildlife should not have been considered a benefit to reducing TDS loadings, as well as pest mgmt. Hopefully, 319 was not used for these.\n7. "Results" - The waterbody remains impaired for DO and turbidity, and the expectation that turbidity will be addressed in 2016. What are the expectations that DO will be addressed with the same BMPs?\n8. Under the Watershed Plan section, place reference in the notes to state when the plan was approved by EPA.\n\nPlease revisit this SS - and clear this up. Headquarters would send this back. Thanks.\n\nAdam Jorge:Change poll listings.10.23.17',
      poll_sources: 'Agriculture',
      prj_hlight_bmp_comments:
        'LDAF began implementing BMPs in 2004 and completed implementation in January 2017. BMPs implemented to date include conservation crop rotation (328 sites; 1,117.4 acres [ac]), residue management (344 sites; 6,008.2 ac), grade stabilization structures (410 sites; 32 ac), irrigation land leveling (464 sites; 4,638.72 ac), shallow water for wildlife (646 sites; 3,112.4 ac), nutrient management (590 sites; 17,052.2 ac), pest management (595 sites; 17,052.2 ac), record keeping (tracking pesticide and nutrient use to avoid overapplication) (748 sites; 17,052.2 ac), and dry seeding (2,232.4 ac).\n\nA watershed implementation plan was developed for Bayou Queue de Tortue in 2013. Bayou Queue de Tortue was made a priority in The Gulf of Mexico Initiative (GoMI). BMP implementation occurred in 2012–2014 to improve ecosystem health in the Gulf of Mexico, and also as part of the National Water Quality Initiative (NWQI) starting in 2014. \n\nAfter reviewing the BMPs implemented and their purposes, LDEQ determined that the most effective in reducing the TDS loads are the grade stabilization structures (constructed between October 2013 and September 2016) and the irrigation land leveling technique (implemented between April 2013 and March 2017) (Figure 2).\n\nLDEQ and its partners began to see steady improvement in the TDS levels in early 2016. LDEQ plans to continue monitoring improvements from BMP implementation, and will use the information to apply to future restoration efforts in other watersheds. ',
      submit_by: null,
      report: null,
      problem_comments:
        'Bayou Queue de Tortue is 56 miles long and flows from the city of Duson to the Mermentau River in Riceville, Louisiana (Figure 1). The bayou receives much of its flow from agricultural runoff from rice and soybean production, and is heavily hydromodified in the upper and middle reaches. Dredging has caused a reduction in flow velocity and eroding spoil banks have increased the amount of solids found in the water column contributing to high turbidity and TDS.\n\nLDEQ has listed the FWP use in this subsegment as impaired since 2002 with suspected causes of impairments including low dissolved oxygen (DO), turbidity, TSS, TDS, sedimentation/siltation, phosphorus (total), nitrate/nitrite (nitrate + nitrite as N), mercury in fish tissue and Fipronil (a broad-spectrum insecticide).\nSuspected sources of impairments were irrigated crop production, atmospheric deposition–toxics, natural conditions, flow alterations from water diversions, and non-irrigated crop production. ',
      partner_fund_comments:
        'DEQ spent a total of $108,350 of Clean Water Act (CWA) section 319 funds on the Bayou Queue de Tortue Project: $10,350 on laboratory analysis and $98,000 on sampling staff and supplies. LDAF and NRCS were instrumental in implementing BMPs in the Bayou Queue de Tortue watershed. A total of 5,827.8 acres are currently under contract. The total payments made in the Bayou Queue de Tortue CWA section 319 project from LDAF are $981,777.67 from 2013 to 2017. The total match received is $1,337,336.58. The conservation programs used to support the goals and objectives of the GoMI are the USDA’s Environmental Quality Incentives Program (EQIP), Conservation Stewardship Program, Wetlands Reserve Program, Grasslands Reserve Program, and the Farm\nand Ranch Lands Protection Program. This watershed project receives EQIP funds which in some cases are leveraged by funds from local and state partners. The sign up for the Bayou Queue de Tortue 319 Project\noccurred in February 2013. The Acadia and Vermilion Soil and Water Conservation District boards set a cap\nof $40,000 per contract with a maximum of one contract per farm entity per parish. A total of 45 applications\nwere received and 38 contracts were written for a total of $1,059,967. The total amount allocated for\nBMPs was $1,075,000. ',
      results_comments:
        'As a result of BMP implementation, water quality has improved, prompting LDEQ to remove TDS as a cause of FWP impairment in the 2014 IR. The FWP use is considered impaired if more than 30 percent of the TDS samples for a reporting period (typically one year) exceed 260 milligrams per liter (mg/L). The ambient water quality network data in Figure 3 shows only one TDS exceedance between May 2012 and September 2016, well below the 30 percent threshold.\n\nIn 2014 the TSS sedimentation/siltation and turbidity impairment classifications were combined and listed simply as turbidity. Although turbidity is still indicated as a cause of impairment to FWP, the ambient and monitoring data show a downward trend throughout 2016. Only two data points exceed 150 nephelometric turbidity units (NTU), a criterion for FWP use support in the Mermentau River (downstream of Bayou Queue de Tortue). In the watershed implementation plan, LDEQ predicted that the average turbidity would be reduced to 149 NTU by 2016. The average of the 2016 monitoring data is 84 NTU, which is 44 percent better than predicted!',
      is_tribal: null,
      tribe_id: null,
      cultural_connection: null,
      is_public: null,
      wb_ids:
        'BAYOU QUEUE DE TORTUE-FROM HEADWATERS TO MERMENTAU RIVER [LA050501_00]',
      pollutants: 'Agriculture',
    },
    {
      ss_seq: 1620,
      rgn_code: '06',
      state: 'LA',
      ss_title:
        'Study Finds Salmon Complete Transatlantic Voyage Using Same Teleportation Chamber As Ancestors',
      ss_overview:
        'Shedding new light on the breeding patterns of the species, an oceanography study published Thursday by Harvard scientists revealed that salmon complete their annual transatlantic voyage using the same teleportation chamber as their ancestors. “This discovery helps solve the mystery of how these fish are able to travel hundreds of thousands of miles through the ocean to make it back to the rivers and streams where they were born,” said lead researcher Andy Nkosi, confirming that each generation of fish passes the exact geographic coordinates to press into the mass transporter’s keypad on to their offspring. “It’s fascinating to see how nature has responded to this unique ecological practice—it’s not an uncommon sight to see bears standing in wait right outside the teleporter in the hopes of catching a salmon as they resolidify after warping to fresh water.” Nkosi added that the salmon typically died shortly after spawning due to their destabilized DNA making their bodies disintegrate.',
      ss_type: '1',
      num_wb_restored: null,
      type1_fiscal_year: 2021,
      publication_date: '2018-02-14T05:00:00Z',
      web_link:
        'https://www.epa.gov/sites/production/files/2016-11/documents/az_middle_gila_508.pdf',
      grts_prj_ids: null,
      notes:
        '1. Abstract - "to improve the health of the water body." Did you partner with LDAF and NRCS to reduce loadings affecting TDS and turbidity, and thus restore the FWP standard? The abstract is not clear in how the LDAF BMPs would have an effect on the TDS and turbidity loadings as it states, "Dredging has caused a reduction in flow velocity and eroding spoil banks have increased the amount of solids." Yet, in the problem paragraph, it list suspected sources as irrigated crop production, atmospheric deposition - toxics. Then it says flow alterations from water Diversions and non-irrigated crop production. This is confusing.\n2. The problem statement will need to coincide with the abstract.\n3. You need photos are the eroding banks, and how it looks now - which hopefully will indicate the difference that the BMPs made in reducing solids to the bayou.\n4.You may want to better link the grade structures with having an effect on reducing TDS. show a picture.\n5. The 2014 IR would be produced from WQ data collected in 2013, and earlier. How could the BMPs that were implemented beginning in April and October, 2013, have had any effect on the load reduction numbers associated with the WQ data that went into the 2014 IR?\n6. Project Highlights - probably should summarize the BMPs - record keeping, for instance, may not be the most convincing unit to help with reducing loads. Also, the shallow water for wildlife should not have been considered a benefit to reducing TDS loadings, as well as pest mgmt. Hopefully, 319 was not used for these.\n7. "Results" - The waterbody remains impaired for DO and turbidity, and the expectation that turbidity will be addressed in 2016. What are the expectations that DO will be addressed with the same BMPs?\n8. Under the Watershed Plan section, place reference in the notes to state when the plan was approved by EPA.\n\nPlease revisit this SS - and clear this up. Headquarters would send this back. Thanks.\n\nAdam Jorge:Change poll listings.10.23.17',
      plncat_types: null,
      prj_hlight_bmp_comments:
        'LDAF began implementing BMPs in 2004 and completed implementation in January 2017. BMPs implemented to date include conservation crop rotation (328 sites; 1,117.4 acres [ac]), residue management (344 sites; 6,008.2 ac), grade stabilization structures (410 sites; 32 ac), irrigation land leveling (464 sites; 4,638.72 ac), shallow water for wildlife (646 sites; 3,112.4 ac), nutrient management (590 sites; 17,052.2 ac), pest management (595 sites; 17,052.2 ac), record keeping (tracking pesticide and nutrient use to avoid overapplication) (748 sites; 17,052.2 ac), and dry seeding (2,232.4 ac).\n\nA watershed implementation plan was developed for Bayou Queue de Tortue in 2013. Bayou Queue de Tortue was made a priority in The Gulf of Mexico Initiative (GoMI). BMP implementation occurred in 2012–2014 to improve ecosystem health in the Gulf of Mexico, and also as part of the National Water Quality Initiative (NWQI) starting in 2014. \n\nAfter reviewing the BMPs implemented and their purposes, LDEQ determined that the most effective in reducing the TDS loads are the grade stabilization structures (constructed between October 2013 and September 2016) and the irrigation land leveling technique (implemented between April 2013 and March 2017) (Figure 2).\n\nLDEQ and its partners began to see steady improvement in the TDS levels in early 2016. LDEQ plans to continue monitoring improvements from BMP implementation, and will use the information to apply to future restoration efforts in other watersheds. ',
      submit_by: null,
      report: null,
      problem_comments:
        'Bayou Queue de Tortue is 56 miles long and flows from the city of Duson to the Mermentau River in Riceville, Louisiana (Figure 1). The bayou receives much of its flow from agricultural runoff from rice and soybean production, and is heavily hydromodified in the upper and middle reaches. Dredging has caused a reduction in flow velocity and eroding spoil banks have increased the amount of solids found in the water column contributing to high turbidity and TDS.\n\nLDEQ has listed the FWP use in this subsegment as impaired since 2002 with suspected causes of impairments including low dissolved oxygen (DO), turbidity, TSS, TDS, sedimentation/siltation, phosphorus (total), nitrate/nitrite (nitrate + nitrite as N), mercury in fish tissue and Fipronil (a broad-spectrum insecticide).\nSuspected sources of impairments were irrigated crop production, atmospheric deposition–toxics, natural conditions, flow alterations from water diversions, and non-irrigated crop production. ',
      partner_fund_comments:
        'DEQ spent a total of $108,350 of Clean Water Act (CWA) section 319 funds on the Bayou Queue de Tortue Project: $10,350 on laboratory analysis and $98,000 on sampling staff and supplies. LDAF and NRCS were instrumental in implementing BMPs in the Bayou Queue de Tortue watershed. A total of 5,827.8 acres are currently under contract. The total payments made in the Bayou Queue de Tortue CWA section 319 project from LDAF are $981,777.67 from 2013 to 2017. The total match received is $1,337,336.58. The conservation programs used to support the goals and objectives of the GoMI are the USDA’s Environmental Quality Incentives Program (EQIP), Conservation Stewardship Program, Wetlands Reserve Program, Grasslands Reserve Program, and the Farm\nand Ranch Lands Protection Program. This watershed project receives EQIP funds which in some cases are leveraged by funds from local and state partners. The sign up for the Bayou Queue de Tortue 319 Project\noccurred in February 2013. The Acadia and Vermilion Soil and Water Conservation District boards set a cap\nof $40,000 per contract with a maximum of one contract per farm entity per parish. A total of 45 applications\nwere received and 38 contracts were written for a total of $1,059,967. The total amount allocated for\nBMPs was $1,075,000. ',
      results_comments:
        'As a result of BMP implementation, water quality has improved, prompting LDEQ to remove TDS as a cause of FWP impairment in the 2014 IR. The FWP use is considered impaired if more than 30 percent of the TDS samples for a reporting period (typically one year) exceed 260 milligrams per liter (mg/L). The ambient water quality network data in Figure 3 shows only one TDS exceedance between May 2012 and September 2016, well below the 30 percent threshold.\n\nIn 2014 the TSS sedimentation/siltation and turbidity impairment classifications were combined and listed simply as turbidity. Although turbidity is still indicated as a cause of impairment to FWP, the ambient and monitoring data show a downward trend throughout 2016. Only two data points exceed 150 nephelometric turbidity units (NTU), a criterion for FWP use support in the Mermentau River (downstream of Bayou Queue de Tortue). In the watershed implementation plan, LDEQ predicted that the average turbidity would be reduced to 149 NTU by 2016. The average of the 2016 monitoring data is 84 NTU, which is 44 percent better than predicted!',
      is_tribal: null,
      tribe_id: null,
      cultural_connection: null,
      is_public: null,
      wb_ids:
        'BAYOU QUEUE DE TORTUE-FROM HEADWATERS TO MERMENTAU RIVER [LA050501_00]',
      plts: 'Other',
    },
  ],
  hasMore: false,
  limit: 25,
  offset: 0,
  count: 1,
  links: [
    {
      rel: 'self',
      href: 'https://ordsstage.rtpnc.epa.gov/ords/grts/grts_rest_apex/sshuc/GetSSByHUC12/080802020105',
    },
    {
      rel: 'describedby',
      href: 'https://ordsstage.rtpnc.epa.gov/ords/grts/grts_rest_apex/metadata-catalog/sshuc/GetSSByHUC12/item',
    },
    {
      rel: 'first',
      href: 'https://ordsstage.rtpnc.epa.gov/ords/grts/grts_rest_apex/sshuc/GetSSByHUC12/080802020105',
    },
  ],
} as const;
