export const usgsStaParameters = [
  {
    staParameterCode: '00010',
    staDescription: 'Temperature, water',
    hmwCategory: 'primary',
    hmwOrder: 3,
    hmwName: 'Water temperature',
    hmwUnits: '°F',
  },
  {
    staParameterCode: '00011',
    staDescription: 'Temperature, water',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Water temperature',
    hmwUnits: '°F',
  },
  {
    staParameterCode: '00020',
    staDescription: 'Temperature, air',
    hmwCategory: 'primary',
    hmwOrder: 4,
    hmwName: 'Air temperature',
    hmwUnits: '°F',
  },
  {
    staParameterCode: '00021',
    staDescription: 'Temperature, air',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Air temperature',
    hmwUnits: '°F',
  },
  {
    staParameterCode: '00025',
    staDescription: 'Air pressure',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Air pressure',
    hmwUnits: 'mm/Hg',
  },
  {
    staParameterCode: '00030',
    staDescription: 'Solar radiation',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Sunlight',
    hmwUnits: 'cal/cm2/d',
  },
  {
    staParameterCode: '00035',
    staDescription: 'Wind speed',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Wind speed',
    hmwUnits: 'mph',
  },
  {
    staParameterCode: '00036',
    staDescription: 'Wind direction',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Wind direction',
    hmwUnits: 'Deg',
  },
  {
    staParameterCode: '00045',
    staDescription: 'Precipitation',
    hmwCategory: 'primary',
    hmwOrder: 5,
    hmwName: 'Rainfall',
    hmwUnits: 'in',
  },
  {
    staParameterCode: '00047',
    staDescription: 'Pressure, diss gases',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: ' ',
    hmwUnits: 'mm/Hg',
  },
  {
    staParameterCode: '00048',
    staDescription: 'Pressure, diss gases, %saturation',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: ' ',
    hmwUnits: '%',
  },
  {
    staParameterCode: '00052',
    staDescription: 'Relative humidity',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Relative humidity',
    hmwUnits: '%',
  },
  {
    staParameterCode: '00053',
    staDescription: 'Surface area',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Waterbody surface area',
    hmwUnits: 'ac',
  },
  {
    staParameterCode: '00054',
    staDescription: 'Reservoir storage',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Water availability in reservoir',
    hmwUnits: 'ac-ft',
  },
  {
    staParameterCode: '00055',
    staDescription: 'Stream velocity',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Stream speed at monitoring point',
    hmwUnits: 'ft/sec',
  },
  {
    staParameterCode: '00060',
    staDescription: 'Discharge',
    hmwCategory: 'primary',
    hmwOrder: 2,
    hmwName: 'Flow rate',
    hmwUnits: 'ft³/s',
  },
  {
    staParameterCode: '00061',
    staDescription: 'Discharge, instant',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Flow rate',
    hmwUnits: 'ft³/s',
  },
  {
    staParameterCode: '00065',
    staDescription: 'Gage height',
    hmwCategory: 'primary',
    hmwOrder: 1,
    hmwName: 'Water level',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '00090',
    staDescription: 'Redox potential',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: ' ',
    hmwUnits: 'mV',
  },
  {
    staParameterCode: '00095',
    staDescription: 'Specific cond at 25C',
    hmwCategory: 'primary',
    hmwOrder: 6,
    hmwName: 'Electrical conductivity (indicator of saltiness)',
    hmwUnits: 'µS/cm @25C',
  },
  {
    staParameterCode: '00193',
    staDescription: 'Precipitation, defined period',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Rainfall',
    hmwUnits: 'in',
  },
  {
    staParameterCode: '00300',
    staDescription: 'Dissolved oxygen',
    hmwCategory: 'primary',
    hmwOrder: 7,
    hmwName: 'Dissolved oxygen concentration',
    hmwUnits: 'mg/l',
  },
  {
    staParameterCode: '00301',
    staDescription: 'Diss oxygen saturtn',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Dissolved oxygen percent saturation',
    hmwUnits: '% saturatn',
  },
  {
    staParameterCode: '00400',
    staDescription: 'pH',
    hmwCategory: 'primary',
    hmwOrder: 9,
    hmwName: 'Acidity',
    hmwUnits: 'std units',
  },
  {
    staParameterCode: '00401',
    staDescription: 'Cations minus anions',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: ' ',
    hmwUnits: 'meq',
  },
  {
    staParameterCode: '00480',
    staDescription: 'Salinity',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Salinity',
    hmwUnits: 'ppth',
  },
  {
    staParameterCode: '00630',
    staDescription: 'NO3+NO2, wu, conc as N',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Nutrients-Nitrogen',
    hmwUnits: 'mg/l as N',
  },
  {
    staParameterCode: '00665',
    staDescription: 'Phosphorus, wu as P',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Nutrient-Phosphorus',
    hmwUnits: 'mg/l as P',
  },
  {
    staParameterCode: '00666',
    staDescription: 'Phosphorus, wf',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Nutrient-Phosphorus',
    hmwUnits: 'mg/l as P',
  },
  {
    staParameterCode: '32217',
    staDescription: 'Chlorophyll a,fm,unc',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Algae',
    hmwUnits: 'µg/l',
  },
  {
    staParameterCode: '32283',
    staDescription: 'DEPRECATED Chlorophyll fluoresce, in situ',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: ' ',
    hmwUnits: 'RFU',
  },
  {
    staParameterCode: '32284',
    staDescription: 'Chlorophyll a, total',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Algae',
    hmwUnits: 'µg/l',
  },
  {
    staParameterCode: '32295',
    staDescription: 'fDOM, water, in situ',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Dissolved organic matter',
    hmwUnits: 'g/l QSE',
  },
  {
    staParameterCode: '32315',
    staDescription: 'Relative fChl, water, in situ',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Algae',
    hmwUnits: 'RFU',
  },
  {
    staParameterCode: '32316',
    staDescription: 'fChl, water, in situ',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Algae',
    hmwUnits: 'µg/l',
  },
  {
    staParameterCode: '32318',
    staDescription: 'DEPRECATED Chlorophylls,in situ',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: ' ',
    hmwUnits: 'µg/l',
  },
  {
    staParameterCode: '32319',
    staDescription: 'fPC, water, in situ',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Blue-green algae, cyanobacteria',
    hmwUnits: 'µg/l',
  },
  {
    staParameterCode: '32320',
    staDescription: 'DEPRECATED Chlorophylls fluoresce,in situ',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: ' ',
    hmwUnits: 'RFU',
  },
  {
    staParameterCode: '32321',
    staDescription: 'Relative fPC, water, in situ',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Blue-green algae, cyanobacteria',
    hmwUnits: 'RFU',
  },
  {
    staParameterCode: '32322',
    staDescription: 'Relative fDOM, water, in situ',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Dissolved organic matter',
    hmwUnits: 'RFU',
  },
  {
    staParameterCode: '32330',
    staDescription: 'fDOM, w, in situ',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Dissolved organic matter',
    hmwUnits: 'mg/l',
  },
  {
    staParameterCode: '32341',
    staDescription: 'fOB, water, in situ',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Optical brighteners (from detergents)',
    hmwUnits: 'µg/L PTSA',
  },
  {
    staParameterCode: '50050',
    staDescription: 'Flow, conduit or TP',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: ' ',
    hmwUnits: 'mgd',
  },
  {
    staParameterCode: '51289',
    staDescription: 'OrthoPO4, in situ as P',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Algae and plant nutrient-Phosphorus',
    hmwUnits: 'mg/l as P',
  },
  {
    staParameterCode: '61055',
    staDescription: 'Water level, depth MP',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Well depth',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '62361',
    staDescription: 'DEPRECATED Chlorophyll, in situ',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: ' ',
    hmwUnits: 'µg/l',
  },
  {
    staParameterCode: '62602',
    staDescription: 'Atmos press, corr',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Air pressure',
    hmwUnits: 'in/Hg',
  },
  {
    staParameterCode: '62603',
    staDescription: 'Air pressure',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Air pressure',
    hmwUnits: 'in/Hg',
  },
  {
    staParameterCode: '62605',
    staDescription: 'Air pressure',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Air pressure',
    hmwUnits: 'in/H2O',
  },
  {
    staParameterCode: '62610',
    staDescription: 'Elevation, GW, NGVD29',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Groundwater level',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '62611',
    staDescription: 'Elevation, GW, NAVD88',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Groundwater level',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '62614',
    staDescription: 'Elevation, lake/res, NGVD29',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Lake or reservoir water level',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '62615',
    staDescription: 'Elevation, lake/res, NAVD88',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Lake or reservoir water level',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '62616',
    staDescription: 'Elevation, lake/res, NGVD29',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Lake or reservoir water level',
    hmwUnits: 'm',
  },
  {
    staParameterCode: '62619',
    staDescription: 'Elevation, ocean/est, NGVD29',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Ocean or estuary water level',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '62620',
    staDescription: 'Elevation, ocean/est, NAVD88',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Ocean or estuary water level',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '62623',
    staDescription: 'Tide stage',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Tide stage',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '62625',
    staDescription: 'Wind speed',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Wind speed',
    hmwUnits: 'm/sec',
  },
  {
    staParameterCode: '63160',
    staDescription: 'Stream level, NAVD',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Stream water level',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '63680',
    staDescription: 'Turbidity, FNU',
    hmwCategory: 'primary',
    hmwOrder: 8,
    hmwName: 'Water clarity',
    hmwUnits: 'FNU',
  },
  {
    staParameterCode: '63682',
    staDescription: 'Turbidity, FBU',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Water clarity',
    hmwUnits: 'FBU',
  },
  {
    staParameterCode: '70301',
    staDescription: 'Diss solids, calcd',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Total dissolved solids',
    hmwUnits: 'mg/l',
  },
  {
    staParameterCode: '72008',
    staDescription: 'Depth, well, LSD',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Well depth',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '72019',
    staDescription: 'Water level, depth LSD',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Well depth',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '72022',
    staDescription: 'Reservoir storage',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Water availability in reservoir',
    hmwUnits: 'Mgal',
  },
  {
    staParameterCode: '72036',
    staDescription: 'Reservoir storage',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Water availability in reservoir',
    hmwUnits: 'Kac-ft',
  },
  {
    staParameterCode: '72189',
    staDescription: 'Snow depth',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Snow cover depth',
    hmwUnits: 'm',
  },
  {
    staParameterCode: '72192',
    staDescription: 'Precipitation, cumul',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Rainfall',
    hmwUnits: 'in',
  },
  {
    staParameterCode: '72194',
    staDescription: 'Precipitation, cumul',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Rainfall',
    hmwUnits: 'mm',
  },
  {
    staParameterCode: '72199',
    staDescription: 'Depth, water column',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Water depth',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '72213',
    staDescription: 'Turbidity, FBRU',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Water clarity',
    hmwUnits: 'FBRU',
  },
  {
    staParameterCode: '72279',
    staDescription: 'Tidal elev, NOS',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Tide stage',
    hmwUnits: 'ft',
  },
  {
    staParameterCode: '72285',
    staDescription: 'Mean wave period',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Mean wave speed',
    hmwUnits: 'seconds',
  },
  {
    staParameterCode: '72286',
    staDescription: 'Significant wave ht',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Wave height',
    hmwUnits: 'm',
  },
  {
    staParameterCode: '72287',
    staDescription: 'Significant wave pd',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Wave speed',
    hmwUnits: 'seconds',
  },
  {
    staParameterCode: '72288',
    staDescription: 'Maximum wave height',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Maximum wave height',
    hmwUnits: 'm',
  },
  {
    staParameterCode: '74207',
    staDescription: 'Soil moisture',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: 'Soil moisture',
    hmwUnits: '%',
  },
  {
    staParameterCode: '75969',
    staDescription: 'Air pressure',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Barometric pressure',
    hmwUnits: 'mbar',
  },
  {
    staParameterCode: '81904',
    staDescription: 'Stream velocity, point',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: 'Stream speed at monitoring point',
    hmwUnits: 'ft/sec',
  },
  {
    staParameterCode: '82127',
    staDescription: 'Wind speed',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Wind speed',
    hmwUnits: 'knots',
  },
  {
    staParameterCode: '85583',
    staDescription: 'Temperature, intragrav water',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Water temperature',
    hmwUnits: '°F',
  },
  {
    staParameterCode: '90860',
    staDescription: 'Salinity, wu, at 25C',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Salinity',
    hmwUnits: 'PSU',
  },
  {
    staParameterCode: '91049',
    staDescription: 'NO3+NO2, wu as N',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Algae and plant nutrients-Nitrogen',
    hmwUnits: 'lb/d as N',
  },
  {
    staParameterCode: '91058',
    staDescription: 'Total nitrogen, wu',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Algae and plant nutrients-Nitrogen',
    hmwUnits: 'lb/day',
  },
  {
    staParameterCode: '99065',
    staDescription: 'Gage height',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Water level',
    hmwUnits: 'm',
  },
  {
    staParameterCode: '99133',
    staDescription: 'NO3+NO2,water,insitu as N',
    hmwCategory: 'primary',
    hmwOrder: 10,
    hmwName: 'Algae and plant nutrients-Nitrogen',
    hmwUnits: 'mg/l as N',
  },
  {
    staParameterCode: '99134',
    staDescription: 'DOC,water,insitu,reg',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: 'Estimated organic carbon concentration',
    hmwUnits: 'mg/l',
  },
  {
    staParameterCode: '99137',
    staDescription: 'Nitrate, in situ as N',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Algae and plant nutrients-Nitrogen',
    hmwUnits: 'mg/l as N',
  },
  {
    staParameterCode: '99141',
    staDescription: 'CO2, water, diss, in situ',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Carbon dioxide concentration',
    hmwUnits: 'mg/l',
  },
  {
    staParameterCode: '99220',
    staDescription: 'Chloride, wu',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Chloride concentration',
    hmwUnits: 'mg/l',
  },
  {
    staParameterCode: '99398',
    staDescription: 'Sodium, wf, estim',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: 'Estimated sodium concentration',
    hmwUnits: 'mg/l',
  },
  {
    staParameterCode: '99404',
    staDescription: 'Chloride, wf, estim',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: 'Estimated chloride concentration',
    hmwUnits: 'mg/l',
  },
  {
    staParameterCode: '99407',
    staDescription: 'E coli, by regr',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: 'Estimated bacteria concentration',
    hmwUnits: 'cfu/100ml',
  },
  {
    staParameterCode: '99409',
    staDescription: 'Susp sediment,wu,est',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: 'Estimated amount of suspended sediments',
    hmwUnits: 'mg/l',
  },
  {
    staParameterCode: '99772',
    staDescription: 'Precipitation',
    hmwCategory: 'secondary',
    hmwOrder: null,
    hmwName: 'Rainfall',
    hmwUnits: 'mm',
  },
  {
    staParameterCode: '99988',
    staDescription: 'PAR, average',
    hmwCategory: 'exclude',
    hmwOrder: null,
    hmwName: 'Average amount of light available for photosynthesis',
    hmwUnits: 'µmol/m2/s',
  },
];
