export const usgsStaParameters = [
  {
    staParameterCode: '00065',
    staDescription: 'Gage height',
    hmwName: 'Water height',
    hmwUnits: 'ft',
    hmwOrder: 1,
  },
  {
    staParameterCode: '00060',
    staDescription: 'Discharge',
    hmwName: 'Flow',
    hmwUnits: 'CFS',
    hmwOrder: 2,
  },
  {
    staParameterCode: '00061',
    staDescription: 'Discharge, instant',
    hmwName: 'Flow',
    hmwUnits: 'CFS',
    hmwOrder: 3,
  },
  {
    staParameterCode: '00300',
    staDescription: 'Dissolved oxygen',
    hmwName: 'Dissolved oxygen',
    hmwUnits: 'mg/L',
    hmwOrder: 4,
  },
  {
    staParameterCode: '00400',
    staDescription: 'pH',
    hmwName: 'pH',
    hmwUnits: '',
    hmwOrder: 5,
  },
  {
    staParameterCode: '00095',
    staDescription: 'Specific cond at 25C',
    hmwName: 'Salinity',
    hmwUnits: 'uS/cm²',
    hmwOrder: 6,
  },
  {
    staParameterCode: '00011',
    staDescription: 'Temperature, water',
    hmwName: 'Water temperature',
    hmwUnits: '°F',
    hmwOrder: 7,
  },
  {
    staParameterCode: '72213',
    staDescription: 'Turbidity, FBRU',
    hmwName: 'Water cloudiness',
    hmwUnits: 'FBRU',
    hmwOrder: 8,
  },
  {
    staParameterCode: '63682',
    staDescription: 'Turbidity, FBU',
    hmwName: 'Water cloudiness',
    hmwUnits: 'FBU',
    hmwOrder: 9,
  },
  {
    staParameterCode: '63680',
    staDescription: 'Turbidity, FNU',
    hmwName: 'Water cloudiness',
    hmwUnits: 'FNU',
    hmwOrder: 10,
  },
];
