export const usgsStaParameters = [
  {
    staParameterCode: '00065',
    staDescription: 'Gage height',
    hmwName: 'Water Level (Gage Height)',
    hmwUnits: 'ft',
    hmwOrder: 1,
  },
  {
    staParameterCode: '00060',
    staDescription: 'Discharge',
    hmwName: 'Daily Average Flow (Discharge)',
    hmwUnits: 'CFS',
    hmwOrder: 2,
  },
  {
    staParameterCode: '00061',
    staDescription: 'Discharge, instant',
    hmwName: 'Current Flow (Discharge)',
    hmwUnits: 'CFS',
    hmwOrder: 3,
  },
  {
    staParameterCode: '00300',
    staDescription: 'Dissolved oxygen',
    hmwName: 'Dissolved Oxygen',
    hmwUnits: 'mg/L',
    hmwOrder: 4,
  },
  {
    staParameterCode: '00400',
    staDescription: 'pH',
    hmwName: 'Acidity (pH)',
    hmwUnits: ' ',
    hmwOrder: 5,
  },
  {
    staParameterCode: '00095',
    staDescription: 'Specific cond at 25C',
    hmwName: 'Saltiness (Specific Conductance)',
    hmwUnits: 'μS/cm²',
    hmwOrder: 6,
  },
  {
    staParameterCode: '00011',
    staDescription: 'Temperature, water',
    hmwName: 'Water Temperature',
    hmwUnits: '°F',
    hmwOrder: 7,
  },
  {
    staParameterCode: '72213',
    staDescription: 'Turbidity, FBRU',
    hmwName: 'Water cloudiness (Turbidity)',
    hmwUnits: 'FBRU',
    hmwOrder: 8,
  },
  {
    staParameterCode: '63682',
    staDescription: 'Turbidity, FBU',
    hmwName: 'Water cloudiness (Turbidity)',
    hmwUnits: 'FBU',
    hmwOrder: 9,
  },
  {
    staParameterCode: '63680',
    staDescription: 'Turbidity, FNU',
    hmwName: 'Water cloudiness (Turbidity)',
    hmwUnits: 'FNU',
    hmwOrder: 10,
  },
  {
    staParameterCode: '00630',
    staDescription: 'NO3+NO2, wu, conc as N',
    hmwName: 'Nitrate-Nitrite',
    hmwUnits: 'mg/L',
    hmwOrder: 11,
  },
  {
    staParameterCode: '72019',
    staDescription: 'Water level, depth LSD',
    hmwName: 'Well depth',
    hmwUnits: 'ft',
    hmwOrder: 12,
  },
];
