# This is a basic workflow to help you get started with Actions

name: Staging Deploy

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch    branches: [ staging ]
  push:
    branches: [staging]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  changes:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: staging

    outputs:
      workflows: ${{ steps.filter.outputs.workflows }}
      app: ${{ steps.filter.outputs.app }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          base: staging
          filters: |
            workflows:
              - '.github/workflows/staging.yml'
            app:
              - 'app/**'

  app:
    # Check if this folder has any changes
    needs: changes
    if: ${{
      needs.changes.outputs.app == 'true' ||
      needs.changes.outputs.workflows == 'true' }}

    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: staging

    # Set environment variables
    env:
      APP_NAME: mywaterway-stage
      APP_NAME_ATTAINS: mywaterway-attains
      CF_ORG: ${{ secrets.CF_ORG }}
      CF_SPACE: ${{ secrets.CF_SPACE_STAGING }}
      CF_STACK: cflinuxfs4
      CF_USER_STAGING: ${{ secrets.CF_USER_STAGING }}
      CF_PASSWORD_STAGING: ${{ secrets.CF_PASSWORD_STAGING }}
      CF_S3_PUB_ACCESS_KEY: ${{ secrets.CF_STAGING_S3_PUB_ACCESS_KEY }}
      CF_S3_PUB_BUCKET_ID: ${{ secrets.CF_STAGING_S3_PUB_BUCKET_ID }}
      CF_S3_PUB_REGION: ${{ secrets.CF_STAGING_S3_PUB_REGION }}
      CF_S3_PUB_SECRET_KEY: ${{ secrets.CF_STAGING_S3_PUB_SECRET_KEY }}
      CF_ATTAINS_S3_PUB_ACCESS_KEY: ${{ secrets.CF_ATTAINS_STAGING_S3_PUB_ACCESS_KEY }}
      CF_ATTAINS_S3_PUB_BUCKET_ID: ${{ secrets.CF_ATTAINS_STAGING_S3_PUB_BUCKET_ID }}
      CF_ATTAINS_S3_PUB_REGION: ${{ secrets.CF_ATTAINS_STAGING_S3_PUB_REGION }}
      CF_ATTAINS_S3_PUB_SECRET_KEY: ${{ secrets.CF_ATTAINS_STAGING_S3_PUB_SECRET_KEY }}
      GLOSSARY_AUTH: ${{ secrets.GLOSSARY_AUTH }}
      HMW_BASIC_USER_NAME: ${{ secrets.HMW_BASIC_USER_NAME }}
      HMW_BASIC_USER_PWD: ${{ secrets.HMW_BASIC_USER_PWD }}
      VITE_ARCGIS_CLIENT_ID: ${{ secrets.VITE_ARCGIS_CLIENT_ID_STAGING }}
      SERVER_URL: https://mywaterway-stage.app.cloud.gov

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up node and npm
      - uses: actions/setup-node@v4
        with:
          node-version: "22"

      # Run front-end processes (install, lint, test, bundle)
      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/client/.npm
          key: v1-npm-client-deps-${{ hashFiles('**/client/package-lock.json') }}
          restore-keys: v1-npm-client-deps-

      - name: Install front-end dependencies
        run: npm install --legacy-peer-deps
        working-directory: app/client

      - name: Build front-end files and move to server
        run: |
          VITE_ARCGIS_CLIENT_ID="$VITE_ARCGIS_CLIENT_ID" \
            NODE_OPTIONS=--max_old_space_size=6144 \
            npm run build
          cd build
          cp -r * ../../server/app/public
          rm -rf *
        working-directory: app/client

      # Run CloudFoundry/Cloud.gov deployment
      - name: Set up Cloud Foundry CLI
        run: |
          curl -v -L -o cf-cli_amd64.deb 'https://packages.cloudfoundry.org/stable?release=debian64&version=8.8.3&source=github-rel'
          sudo dpkg -i cf-cli_amd64.deb
          cf -v
          cf api https://api.fr.cloud.gov
          cf auth "$CF_USER_STAGING" "$CF_PASSWORD_STAGING"
          cf target -o "$CF_ORG" -s "$CF_SPACE"

      - name: Set application-level variables
        run: |
          cf set-env $APP_NAME "GLOSSARY_AUTH" "$GLOSSARY_AUTH" > /dev/null
          cf set-env $APP_NAME "HMW_BASIC_USER_NAME" "$HMW_BASIC_USER_NAME" > /dev/null
          cf set-env $APP_NAME "HMW_BASIC_USER_PWD" "$HMW_BASIC_USER_PWD" > /dev/null
          cf set-env $APP_NAME "TZ" "America/New_York" > /dev/null

      - name: Configure Public AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.CF_S3_PUB_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.CF_S3_PUB_SECRET_KEY }}
          aws-region: ${{ env.CF_S3_PUB_REGION }}

      # Sync static content to public S3 bucket
      - name: Sync static content to S3
        run: aws s3 sync . s3://$CF_S3_PUB_BUCKET_ID/data
        working-directory: app/server/app/public/data

      # Set CORS configuration for public S3 bucket
      - name: Set public S3 CORS configuration
        run: aws s3api put-bucket-cors --bucket $CF_S3_PUB_BUCKET_ID --cors-configuration file://s3CORS.json
        working-directory: app/server/app/config

      # Now that front-end is built in server/dist, only push server dir to Cloud.gov
      - name: Deploy application to Cloud.gov
        run: cf push $APP_NAME --strategy rolling -f ../manifest-staging.yml -p . -t 180 -s $CF_STACK
        working-directory: app/server

      - name: Zip artifacts
        run: tar -czf hmwv2.tar.gz server
        working-directory: app

      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hmwv2
          path: app/hmwv2.tar.gz

      - name: Copy ATTAINS NCC endpoints over
        run: cp -rf services-attains.json services.json
        working-directory: app/server/app/public/data/config

      - name: Set ATTAINS version application-level variables
        run: |
          cf set-env $APP_NAME_ATTAINS "GLOSSARY_AUTH" "$GLOSSARY_AUTH" > /dev/null
          cf set-env $APP_NAME_ATTAINS "HMW_BASIC_USER_NAME" "$HMW_BASIC_USER_NAME" > /dev/null
          cf set-env $APP_NAME_ATTAINS "HMW_BASIC_USER_PWD" "$HMW_BASIC_USER_PWD" > /dev/null

      - name: Configure Public AWS Credentials for ATTAINS version
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ env.CF_ATTAINS_S3_PUB_ACCESS_KEY }}
          aws-secret-access-key: ${{ env.CF_ATTAINS_S3_PUB_SECRET_KEY }}
          aws-region: ${{ env.CF_ATTAINS_S3_PUB_REGION }}

      # Sync ATTAINS version static content to public S3 bucket
      - name: Sync static content to S3 for ATTAINS version
        run: aws s3 sync . s3://$CF_ATTAINS_S3_PUB_BUCKET_ID/data
        working-directory: app/server/app/public/data

      # Set CORS configuration for public ATTAINS version S3 bucket
      - name: Set public S3 CORS configuration for ATTAINS version
        run: aws s3api put-bucket-cors --bucket $CF_ATTAINS_S3_PUB_BUCKET_ID --cors-configuration file://s3CORS.json
        working-directory: app/server/app/config

      # Now that front-end is built in server/dist, only push server dir to Cloud.gov
      - name: Deploy ATTAINS version of application to Cloud.gov
        run: cf push $APP_NAME_ATTAINS --strategy rolling -f ../manifest-attains.yml -p . -t 180 -s $CF_STACK
        working-directory: app/server
